packages:
  # all packages in direct subdirs of packages/
  - 'apps/packages/*'
  - 'apps/packages/shared/*'
  - 'apps/packages/plugins/*'
  # all packages in subdirs of components/
  # - 'components/**'
  # exclude packages that are inside test directories
  - '!**/test/**'
